/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2022;

import java.awt.Color;

/**
 *
 * @author shadow
 */
public class JFramePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipale
     */
    public JFramePrincipale() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Affin = new javax.swing.JButton();
        Vigenere = new javax.swing.JButton();
        RSA = new javax.swing.JButton();
        Hill = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TALHAOUI ANAS & QADDOURI IMAD Cryptographie  M2I");

        jPanel1.setLayout(null);

        Affin.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        Affin.setForeground(new java.awt.Color(240, 240, 240));
        Affin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Importation/button_affine.png"))); // NOI18N
        Affin.setBorder(null);
        Affin.setBorderPainted(false);
        Affin.setContentAreaFilled(false);
        Affin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Affin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffinActionPerformed(evt);
            }
        });
        jPanel1.add(Affin);
        Affin.setBounds(770, 30, 200, 80);

        Vigenere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Importation/button_vignere.png"))); // NOI18N
        Vigenere.setToolTipText("");
        Vigenere.setActionCommand("Vigenere");
        Vigenere.setBorderPainted(false);
        Vigenere.setContentAreaFilled(false);
        Vigenere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VigenereActionPerformed(evt);
            }
        });
        jPanel1.add(Vigenere);
        Vigenere.setBounds(770, 150, 200, 80);
        Vigenere.getAccessibleContext().setAccessibleName("Vigenere");

        RSA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Importation/button_rsa.png"))); // NOI18N
        RSA.setBorderPainted(false);
        RSA.setContentAreaFilled(false);
        RSA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSAActionPerformed(evt);
            }
        });
        jPanel1.add(RSA);
        RSA.setBounds(770, 410, 200, 80);

        Hill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Importation/button_hill.png"))); // NOI18N
        Hill.setBorderPainted(false);
        Hill.setContentAreaFilled(false);
        Hill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HillActionPerformed(evt);
            }
        });
        jPanel1.add(Hill);
        Hill.setBounds(770, 280, 200, 80);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Importation/title.png"))); // NOI18N
        jLabel2.setText("  ");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -20, 380, 210);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Importation/bg.jpeg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -30, 1000, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


   
    private void AffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffinActionPerformed
        JFrameAffin a = new JFrameAffin();
        a.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            a.setVisible(true);            a.setVisible(true);    }//GEN-LAST:event_AffinActionPerformed

    private void VigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VigenereActionPerformed
        JFrameVigenere a = new JFrameVigenere();
        a.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        a.setVisible(true);
    }//GEN-LAST:event_VigenereActionPerformed

    private void RSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSAActionPerformed
        JFrameRsa a = new JFrameRsa();
        a.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        a.setVisible(true);
    }//GEN-LAST:event_RSAActionPerformed

    private void HillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HillActionPerformed
        JFrameHill a = new JFrameHill();
        a.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        a.setVisible(true);
    }//GEN-LAST:event_HillActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Affin;
    private javax.swing.JButton Hill;
    private javax.swing.JButton RSA;
    private javax.swing.JButton Vigenere;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
